name: notesheet_tracker
description: A new Flutter project for managing document workflows.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # KEEP THIS LINE (latest version) and ensure it is properly indented:
  supabase_flutter: ^2.5.0 
  
  flutter_dotenv: ^5.2.0 
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  file_picker: ^8.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - supabase.env
